### PR TITLE
Issue 14 IE 11 Fix

### PR DESCRIPTION
**Pull request by russell-tarpley**
Removed CustomEvent polyfill which seemed to cause issues with other
mdl components. Replaced with Helper method. Updated references to
CustomEvent defintion with calls to helper method instead.

### CODE REVIEW

**Comment by sucre666** [comment]
@ahlechandre could you merge this?

**Comment by axdemelas** [comment]
> Sorry for the long time but I'm very busy lately and did not have time to check the PR code. 

Currently, I can't merge this because the changes was in the bundle file instead of in the entry point.

```
.
+-- src
|     +-- stepper
|           +-- stepper.js (entry) <-- You should put it here.
+-- stepper.js (bundle) <-- Where you did.
+-- stepper.min.js (bundle)
```

The JavasScript bundle files (placed in the root directory) are automatically generated by a transpiling process using [Babel](https://github.com/babel/babel-loader) and [Webpack](https://github.com/webpack/webpack). To contribute properly, you should write the changes in entry file and commit so then I can merge this PR.

Optionally, If you want to generate the bundles locally, place your changes in entry point and follows:

``` bash
# Inside mdl-stepper/ folder.
# Install dev dependencies.
npm install
# Build a development version of javascript changes.
npm run dev
# Build a production version of javascript changes.
npm run prod
# Build a production version of javascript changes on WINDOWS.
# npm run prod-windows
```

> Look at _scripts_ in `package.json` to see what internally means each command.

**Comment by russell-tarpley** [comment]
My bad. I don't often work with transpiling processes. I'm holding off for a few though, as I am running into an issue with the stepper actions not triggering that I believe is in relation to my changes.

**Comment by russell-tarpley** [comment]
Alright latest commit is to the entry point and is working in IE 11, Edge, and Chrome browsers. Events are triggering as expected.

**Comment by axdemelas** [comment]
I just made some changes to adjust it to Google code style.

Thanks @Rathxxx for contributing to [v1.1.6](https://github.com/ahlechandre/mdl-stepper/releases/tag/v1.1.6).

**Pull request merged**
